name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - production
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: production
          DEFAULT_BUMP: minor